# Generated by Django 3.2.13 on 2022-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectusermessage_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusermessage',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
