# Generated by Django 4.2.1 on 2023-05-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_field1', models.CharField(max_length=200)),
                ('model_field2', models.DateTimeField(verbose_name='Time Here')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_field3', models.IntegerField(default=0)),
                ('model_above', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customreportapp.testmodel')),
            ],
        ),
    ]
