# Generated by Django 4.2.1 on 2023-05-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customreportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel2',
            name='choice_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
